services:
  - type: static_site
    name: web-portal
    env: static
    plan: free
    buildCommand: npm install && npm run build
    publishPath: ./dist
    pullRequestPreviewsEnabled: false
    branch: main
    rootDir: .
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
